// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	bod "github.com/jadahbakar/kawalrencanamu-backend/internal/master/bod"
	mock "github.com/stretchr/testify/mock"
)

// BodRepository is an autogenerated mock type for the BodRepository type
type BodRepository struct {
	mock.Mock
}

// SearchAll provides a mock function with given fields:
func (_m *BodRepository) SearchAll() ([]bod.Bod, error) {
	ret := _m.Called()

	var r0 []bod.Bod
	if rf, ok := ret.Get(0).(func() []bod.Bod); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bod.Bod)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchById provides a mock function with given fields: Id
func (_m *BodRepository) SearchById(Id int) (bod.Bod, error) {
	ret := _m.Called(Id)

	var r0 bod.Bod
	if rf, ok := ret.Get(0).(func(int) bod.Bod); ok {
		r0 = rf(Id)
	} else {
		r0 = ret.Get(0).(bod.Bod)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(Id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
