// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	bod "github.com/jadahbakar/kawalrencanamu-backend/internal/master/bod"
	mock "github.com/stretchr/testify/mock"
)

// BodService is an autogenerated mock type for the BodService type
type BodService struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *BodService) FindAll() ([]bod.Bod, error) {
	ret := _m.Called()

	var r0 []bod.Bod
	if rf, ok := ret.Get(0).(func() []bod.Bod); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bod.Bod)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *BodService) FindById(id string) (bod.Bod, error) {
	ret := _m.Called(id)

	var r0 bod.Bod
	if rf, ok := ret.Get(0).(func(string) bod.Bod); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bod.Bod)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
